### ISSUE TITLE
Ability to use Gravatar images

### ISSUE THREAD

**Issue by uglybugger** [mattriley/agile-avatars#1]
This is a really useful little app. Thanks again for building it :)

One useful feature (to me, anyway) would be to be able to add avatars just by adding a person's email address and sourcing an image from Gravatar. The Gravatar URL format is pretty trivial to generate and also allows for custom sizing of the image it returns.

A feature like this would make it easier to just enter a bunch of email addresses for a team rather than chase them all individually for profile images.

**Comment by mattriley** [comment]
My pleasure, it was fun to build :)

This is a brilliant idea and shouldn't be hard to implement. I'll see what I can do.

**Comment by mattriley** [comment]
I've added a very first cut of a Gravatar feature. Email addresses need to be entered one-by-one for the time being.

**Comment by mattriley** [comment]
Take another look at it now!
