### ISSUE TITLE
Support HTTPS 

### ISSUE THREAD

**Issue by ineffyble** [mattriley/agile-avatars#2]
Given personal data is accessed by this site, it would be good to have it using & enforcing HTTPS.

This should hopefully be a simple thing to implement, but I can't speak to specifics without knowledge of the hosting/infra situation (happy to help if I can).

**Comment by mattriley** [comment]
No personal data is transmitted; it's entirely a client side app. Nevertheless, HTTPS is a good idea, thanks for the suggestion, and offer of help - I'll let you know if I could use some :)

**Comment by ineffyble** [comment]
I thought that might be the case. But it's worth noting that without HTTPS, an attacker could modify the code to transmit the data.

**Comment by mattriley** [comment]
Done =)
